name: Build

# Simple build workflow
# Runs on every push to master and every pull request to master
# Builds the project and uploads the artifacts
# Runs build.sh to build the project
# Artifact is in build/upload_me.zip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    

jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build
        run: ./build.sh
      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: build/upload_me.zip
