name: Build

# Simple build workflow
# Runs on every push to master and every pull request to master
# Builds the project and uploads the artifacts
# Runs build.sh to build the project
# Artifact is in build/upload_me.zip

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
    

jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts
