name: Publish GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - public_url: gallery # wf
            data_folder: data
            folder: gallery
          - public_url: gallery/galleryNAC # nac
            data_folder: dataNAC
            folder: galleryNAC
          - public_url: gallery/galleryNERC # nerc
            data_folder: dataNERC
            folder: galleryNERC
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build
        run: PUBLIC_URL=${{ matrix.public_url }} VITE_DATA_FOLDER=${{ matrix.data_folder }} ./build.sh
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: build-${{ matrix.folder }}
          path: ${{ matrix.folder }}.zip
  repack-gh-pages:
    name: Repack GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: .
      - name: Unzip all zip from multiple zips
        run: |
          mkdir build-all
          cp build-*/*.zip build-all
          cd build-all
          ls
          unzip '*.zip'
          mv gallery/* .
          rm -rf gallery
          rm *.zip
          ls
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@master
        with:
          path: build-all
  deploy:
    name: Deploy to GitHub Pages
    needs: repack-gh-pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:    
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
