#name: Publish release
#
## Releases artifact from the build workflow
#
#on:
#  workflow_dispatch:
#    inputs:
#      version:
#        description: Name of release (in the format of X.Y.Z and without 'v' prefix)
#        required: true
#      publish:
#        type: boolean
#        description: Would release be published
#        required: true
#        default: true
#      draft:
#        type: boolean
#        description: Publish draft first
#        required: true
#        default: true
#
#jobs:
#  build:
#    name: Create artifacts from master
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '16'
#          cache: 'npm'
#      - name: Install dependencies
#        run: npm ci --legacy-peer-deps
#      - name: Build
#        run: PUBLIC_URL=/gallery npm run build
#      - uses: actions/upload-artifact@master
#        with:
#          name: artifacts
#          path: dist
#  release:
#    name: Create release
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Download artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: artifacts
#          path: build
#      - name: Zip artifacts into a single file
#        run: zip -r upload_me.zip build
#      - name: Create release
#        if: ${{ github.event.inputs.publish }}
#        uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          prerelease: false
#          automatic_release_tag: "v${{ github.event.inputs.version }}"
#          draft: ${{ github.event.inputs.draft }}
#          files: |
#            upload_me.zip
#
