name: Publish release

# Releases artifact from the build workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: Name of release (in the format of X.Y.Z and without 'v' prefix)
        required: true
      publish:
        type: boolean
        description: Would release be published
        required: true
        default: true
      draft:
        type: boolean
        description: Publish draft first
        required: true
        default: true

jobs:
  build:
    name: Create artifacts from master
    runs:
      using: 'docker'
      image: '.github/workflow/Dockerfile'
    strategy:
      matrix:
        include:
          - public_url: gallery # wf
            data_folder: data
          - public_url: galleryNAC # nac
            data_folder: dataNAC
          - public_url: galleryNERC # nerc
            data_folder: dataNERC
    steps:
      - name: Build
        run: PUBLIC_URL=${{ matrix.public_url }} VITE_DATA_FOLDER=${{ matrix.data_folder }} ./build.sh
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: build-${{ matrix.public_url }}
          path: ${{ matrix.public_url }}.zip
          if-no-files-found: error
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: build
      - name: Create release
        if: ${{ github.event.inputs.publish }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "v${{ github.event.inputs.version }}"
          draft: ${{ github.event.inputs.draft }}
          files: |
            build/**/*.zip
