name: Publish release

# Releases artifact from the build workflow

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - public_url: gallery # wf
            data_folder: data
          - public_url: galleryNAC # nac
            data_folder: dataNAC
          - public_url: galleryNERC # nerc
            data_folder: dataNERC
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build
        run: PUBLIC_URL=${{ matrix.public_url }} VITE_DATA_FOLDER=${{ matrix.data_folder }} ./build.sh
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: build-${{ matrix.public_url }}
          path: ${{ matrix.public_url }}.zip
  merge:
    name: Merge zips into one
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          path: .
      - name: Unzip all zip from multiple zips
        run: |
          mkdir build-all
          cp build-*/*.zip build-all
          cd build-all
          ls
          unzip '*.zip'
          rm *.zip
          ls
      - name: Upload raw
        uses: actions/upload-artifact@master
        with:
          name: all
          path: build-all
